name: Build Dev
on:
  workflow_dispatch:
  workflow_call:
env:
  ABC: 'efg'

jobs:
  fetch-dependencies:
    name: Fetch Dependencies
    uses: ./.github/workflows/fetch-deps.yml
    secrets: inherit
    with:
      cache-path: "cache_path_for_dev"

  build-and-push:
    name: Dev - Build & Publish
    runs-on: ubuntu-latest
    needs: fetch-dependencies

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy
      run: echo "Deploying ... dev"
