name: Build Dev
on:
  workflow_dispatch:
  workflow_call:

jobs:
  fetch-dependencies:
    name: Fetch Dependencies
    uses: ./.github/workflows/fetch-deps.yml
    secrets: inherit
    with:
      cache-path: "${{ vars.ABC }}"

  build-and-push:
    name: Dev - Build & Publish
    runs-on: ubuntu-latest
    needs: fetch-dependencies

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy
      run: echo "Deploying ... dev ${{ vars.ABC }}"
