name: Build live
concurrency: production

on:
  workflow_dispatch:

env:

jobs:

  fetch-dependencies:
    name: Fetch Dependencies
    uses: ./.github/workflows/fetch-deps.yml
    secrets: inherit
    with:
      cache-path: "cache_path_for_live"

  build-and-push:
    name: Live - Build & Push Image
    runs-on: ubuntu-latest
    needs: fetch-dependencies

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: echo "deploy live"