name: Commit Tag

on:
  workflow_call:
    inputs:
      deploy-live:
        required: false
        type: boolean
        default: false
      ref:
        required: false
        type: string
jobs:
  commit-tag:
    name: Update git tag
    runs-on: ubuntu-latest  

    steps:

    - name: Git commit
      run: echo "$GITHUB_SHA - $GITHUB_REF - ${{ inputs.ref }} ${{ github.ref_name }}"
      
    - name: Git commit part 2
      run: echo "(${{ (inputs.ref == '') && $GITHUB_SHA) || inputs.ref }}"
      
